# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Allow flexible array literal spacing
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Prefer double quotes for consistency
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Allow flexible else/end alignment in ternary assignments
Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
